config/routes.rb
App::Application.routes.draw do

  match "attachments/:attachment_type/:id", :to => 'attachments#get_attachment', :as => 'get_attachment'
  resources :attachments
  resources :comments

  devise_for :users

  match "home", :to => 'home#index', :as => :user_home

  match 'admin/project_process_units', :to => 'admin#project_process_units'
  match 'admin/client_projects', :to => 'admin#client_projects'
  match "admin", :to => 'admin#index', :as => :admin_home
  match "admin/sizing_data", :to => 'admin#sizing_data', :as => :default_data

  namespace :admin do

    resources :procures do
      collection do
        post "procure_rfq_sections"
        get "procure_rfq_sections_destroy"
        post "procure_additional_po_costs"
        get "procure_additional_po_costs_destroy"
      end
    end

    resources :pipings do

    end

    resources :mechanical_specifications do
      collection do
        post "itemtypes"
        get "itemtypes_destroy"
        post "vendor_requirement"
        get "vendor_requirement_destroy"
        post "datasheet"
        get "datasheet_destroy"
        get "datasheet_item_type"
      end
    end

    resources :relief_rate_calculation_views do
      collection do
        get 'view_generic'
        post 'save_generic'
      end
    end

    resources :scenario_summary_view_details do
      collection do
        get  'view_hydraulic_expansions'
        post 'save_hydraulic_expansions'
      end
    end

    resources :sizing_status_activities do
      collection do
        post 'change_status'
      end
    end

    match "summary_reports/:sizing", :to => 'summary_reports#sizing_summary_pdf', :as => :sizing_summary_pdf

    resources :company_users
    resources :groups
    resources :titles
    resources :units
    resources :roles

    resources :clients do
      member do
        get 'projects'
      end
    end

    resource :dashboard do
      collection do
        get "clients"
        get "projects"
        get "process_units"
        get "setdefault"
      end
    end

    resources :projects do
      member do
        get "edit/:step", :to => "projects#edit", :as => :edit_steps
        post "team_assignment"
        post "vendor_assignment"
        get "assign"
        get "assign_vendors"
        get "process_units"
        get "convert_and_round"
      end
      collection do
        get "project_case_details"
        get "project_details"
        post "update_case_details"
        get "vendor_setups"
        get "quotation"
        get "edit_vendor_schedule_setup"
        get "edit_purchase_vendor_schedule_setup"
        get "edit_as_built_vendor_schedule_setup"
        get "edit_with_shipment_vendor_schedule_setup"
        post "update_vendor_schedule_setup"
        post "update_purchase_vendor_schedule_setup"
        post "update_as_built_vendor_schedule_setup"
        post "update_with_shipment_vendor_schedule_setup"
        get "edit_request_for_quotation_setup"
        post "update_request_for_quotation_setup"
      end
    end

    resources :measure_units

    resources :measurements do
      collection do
        get 'get_measurement_sub_types'
      end
    end

    resources :measurement_sub_types
    resources :unit_of_measurements
    match '/heat_and_material_balances/get_sheet/:id/:name' => 'heat_and_material_balances#get_sheet', :as => 'get_hnm_balance_sheet'
    resources :heat_and_material_balances do
      member do
        post "delete_case"
      end
      collection do
        get "get_stream_nos"
      end
    end

    resources :pipe_roughness

    resources :sizing_criteria_categories
    resources :sizing_criteria_category_types
    resources :sizing_criterias do
      collection do
        get 'show_sizing_criterias'
        post 'add_sizing_criterias_to_project'
      end
    end

    resources :line_sizings do
      collection do
        get 'get_stream_values'
        get 'get_sizing_criteria_types'
        get 'get_sizing_criterias'
        get 'get_sizing_criteria_values'
        get 'line_sizing_summary'
        get 'sizing_criteria_calculation'
        get 'get_flow_regime'
        get 'design_condition_design'
        get 'straight_pipe_thickness_design'
        get 'target_two_phase_regime_estimate'
        get 'calculate_outer_diameter'
        post 'segment_sizing_criteria_calculation'
      end
      member do
        get 'clone'
      end
    end

    resources :vessel_sizings do
      collection do
        get 'get_feed_stream_nos'
        get 'get_top_outlet_stream_nos'
        get 'get_bottom_outlet_stream_nos'
        get 'get_vessel_sizing_hs_water_stream_nos'
        get 'vessel_sizing_summary'
        get 'filter_transfer_data'
        get 'reactor_transfer_data'
        get 'design_conditions_calculate'
        get 'mechanical_design_calculate'
        get 'get_nozzle_od'
        get 'feed_nozzle_calculation'
        get 'top_outlet_nozzle_calculation'
        get 'bottom_outlet_nozzle_calculation'
        get 'decanter_calculation'
        get 'horizontal_separator_calculation'
        get 'settler_calculation'
        get 'vertical_separator_calculation'
      end
      member do
        get 'clone'
      end

    end

    resources :pump_sizings do
      collection do
        get 'get_stream_values'
        get 'get_discharge_stream_nos'
        get 'clone_circuit_piping'
        get 'pump_sizing_summary'
        get 'suction_side_hydraulics'
        get 'discharge_side_hydraulics'
        get 'design_pump_centrifugal'
        get 'design_pump_reciprocation'
        get 'pump_suction_design'
        get 'equalize'
        get 'new_stream_property_changer'
        get 'get_change_properties_stream_values'
        get 'system_loss_calculate'
      end
      member do
        get 'clone'
      end
    end

    resources :compressor_sizings do
      collection do
        get 'get_stream_values'
        get 'get_discharge_stream_nos'
        get 'clone_circuit_piping'
        get 'compressor_sizing_summary'
        post 'add_compressor_sizing_mode'
        post 'edit_compressor_sizing_mode'
        post 'delete_compressor_sizing_mode'
        get 'suction_pipings'
        get 'discharges'
        get 'discharge_circuit_pipings'
        get 'discharge_circuit_piping_div'
        get 'suction_calculate'
        get 'discharge_calculate'
        get "centrifugal_design_calculate"
        get "reciprocation_design_calculate"
        get "rd_interstage_piping_calculate"
        get "cd_interstage_piping_calculate"
      end
      member do
        get 'clone'
      end
    end

    resources :driver_sizings do

    end

    resources :electric_motors do
      collection do
        get 'electric_motor_summary'
        get 'get_equiment_tag_by_equiment_type'
        get 'get_rotating_equipment_details'
      end
      member do
        get 'clone'
      end
    end

    resources :steam_turbines do
      collection do
        get 'get_stream_values'
        get 'steam_turbine_summary'
        get 'get_equiment_tag_by_equiment_type'
        get 'get_rotating_equipment_details'
        get 'steam_turbine_design_calculate'
        get 'estimate_efficiency_calculation'
      end
      member do
        get 'clone'
      end
    end

    resources :hydraulic_turbines do
      collection do
        get 'get_stream_values'
        get 'get_discharge_stream_nos'
        get 'hydraulic_turbine_summary'
        get 'suction_calculation'
        get 'get_equiment_tag_by_equiment_type'
        get 'get_rotating_equipment_details'
        get 'hprt_suctionside_hydraulics'
        get 'hprt_dischargeside_hydraulics'
        get 'hydraulic_turbine_design'
      end
      member do
        get 'clone'
      end
    end

    resources :turbo_expanders do
      collection do
        get 'get_stream_values'
        get 'get_expander_design_stream_values'
        get 'turbo_expanders_summary'
        get 'expander_design_calculation'
        get 'get_equiment_tag_by_equiment_type'
        get 'get_rotating_equipment_details'
      end
      member do
        get 'clone'
      end
    end

    resources :control_valve_sizings do
      collection do
        get 'get_stream_values'
        get 'get_discharge_stream_nos'
        get 'control_valve_sizing_summary'
        get 'bypass_design_calculation'
        get 'control_valve_design_calculation'
        get 'upstream_calculate'
        get 'downstream_calculate'
      end
      member do
        get 'clone'
      end
    end

    resources :flow_element_sizings do
      collection do
        get 'get_stream_values'
        get 'get_discharge_stream_nos'
        get 'flow_element_sizing_summary'
        get 'upstream_calculate'
        get 'downstream_calculate'
        get 'get_pipe_diameter'
        get 'get_orifice_types'
        get 'orifice_design'
      end
      member do
        get 'clone'
      end
    end

    resources :storage_tank_sizings do
      collection do
        get 'get_stream_values'
        get 'store_tank_sizing_summary'
        get 'design_conditions_calculate'
        get 'atm_low_pressure_storage_calculate'
        get 'pvapor_calculate'
        get 'pressure_storage_calculate'
        get 'mechanical_design_calculate'
        get 'atm_standardize_calculate'
        get 'ps_standardize_calculate'
      end
      member do
        get 'clone'
      end
    end

    resources :column_sizings do
      collection do
        get 'get_stream_values'
        get 'column_sizing_summary'
        get 'system_definition_calculation'
        get 'minimum_column_stages_calculation'
        get 'minimum_column_stages_winn_modified_calculation'
        post 'minimum_reflux_ratio_calculation'
      end
      member do
        get 'clone'
      end
    end

    resources :heat_exchanger_sizings do
      collection do
        get 'get_stream_values'
        get 'heat_exchanger_sizing_summary'
        get 'change_tube_od'
      end
      member do
        get 'clone'
      end
    end

app/models/sizing_criteria_category.rb
class SizingCriteriaCategory < ActiveRecord::Base
  
  belongs_to :company
  has_many :sizing_criterias 
  has_many :sizing_criteria_category_types, :dependent => :destroy
  has_many :project_sizing_criterias
  has_many :line_sizings
  
  validates_presence_of :name, :company_id
end

app/models/sizing_criteria_category_type.rb
class SizingCriteriaCategoryType < ActiveRecord::Base
  belongs_to :sizing_criteria_category
  has_many :sizing_criterias,  :dependent => :destroy
  has_many :project_sizing_criterias, :dependent => :destroy
  has_many :line_sizings
  
  validates_presence_of :name, :sizing_criteria_category_id
end

app/controllers/admin/sizing_criteria_categories_controller.rb
class Admin::SizingCriteriaCategoriesController < AdminController
  
  def new
    @sizing_criteria_category = @company.sizing_criteria_categories.new
    
    render :layout => false
  end
  
  def create
    sizing_criteria_category = params[:sizing_criteria_category]
    sizing_criteria_category[:created_by] = sizing_criteria_category[:updated_by] = current_user.id    
    @sizing_criteria_category = SizingCriteriaCategory.new(sizing_criteria_category)
    
    respond_to do |format|
      if @sizing_criteria_category.save
        format.js 
      else
        format.js 
      end
    end    
  end
  
  def edit
    @sizing_criteria_category = @company.sizing_criteria_categories.find(params[:id])
    
    render :layout => false
  end
  
  def update
    sizing_criteria_category = params[:sizing_criteria_category]
    sizing_criteria_category[:updated_by] = current_user.id
    
    @sizing_criteria_category = @company.sizing_criteria_categories.find(params[:id])
    
    respond_to do |format|
      if @sizing_criteria_category.update_attributes(sizing_criteria_category)
        format.js 
      else
        format.js 
      end
    end 
    
  end
    
  def destroy
    sizing_criteria_category = @company.sizing_criteria_categories.find(params[:id])
    if sizing_criteria_category.destroy
      flash[:notice] = "Deleted #{sizing_criteria_category.name} successfully."
      redirect_to admin_sizing_criterias_path
    end    
  end
  
end

app/helpers/admin/sizing_criteria_categories_helper.rb
module Admin::SizingCriteriaCategoriesHelper
end

app/views/admin/sizing_criteria_categories/_form.html.erb
<%= form_for sizing_criteria_category, :url => sizing_criteria_category.new_record? ? admin_sizing_criteria_categories_path : admin_sizing_criteria_category_path(sizing_criteria_category), :remote=>true,:html => {:style => 'width:400px;'} do |f| %>
	<%= f.error_messages %>	
	<%= f.hidden_field :company_id%>
	<div class="form-element-last">
		<%= f.label :name%><br>
		<%= f.text_field :name%>
	</div>
	<div class="form-buttons">
		<%= f.submit sizing_criteria_category.new_record? ? 'Create' : 'Update'%>		
  	</div>
<% end%>

app/views/admin/sizing_criteria_categories/_index.html.erb
<div class="sizing_criteria_categories">
	<h4 style="margin-bottom:8px;">List of Sizing Criteria Categories</h4>
  <% if user_access_type == 1 %>
    <%= link_to 'Add New Sizing Criteria Categories', new_admin_sizing_criteria_category_path, {:id => "new_admin_sizing_criteria_category"} %>
  <% end %>
  <br>
  <table id="sizing_criteria_categories_list">
    <tr>
      <th>Name</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    <% for sizing_criteria_category in sizing_criteria_categoires %>
      <tr class="odd">
        <td colspan="3">
          <%= sizing_criteria_category.name %>
          <span style="float:right;">				
					<%= link_to 'Edit', edit_admin_sizing_criteria_category_path(sizing_criteria_category), :class => "edit_admin_sizing_criteria_category" %>&nbsp;|
            <%= link_to 'Delete', admin_sizing_criteria_category_path(sizing_criteria_category), :method => "delete", :confirm => "Are you sure?" %>&nbsp;|
            <%= link_to 'Add Types', new_admin_sizing_criteria_category_type_path(:sizing_criteria_category_id => sizing_criteria_category.id), {:class => "new_admin_sizing_criteria_category_type"} %>
				</span>
        </td>
      </tr>
      <% for sizing_criteria_category_type in sizing_criteria_category.sizing_criteria_category_types %>
        <tr>
          <td><%= sizing_criteria_category_type.name %></td>
          <td><%= link_to 'Edit', edit_admin_sizing_criteria_category_type_path(sizing_criteria_category_type), :class => "edit_admin_sizing_criteria_category_type" %></td>
          <td><%= link_to 'Delete', admin_sizing_criteria_category_type_path(sizing_criteria_category_type), :method => "delete", :confirm => "Are you sure?" %></td>
        </tr>
      <% end %>
      <% if sizing_criteria_category.sizing_criteria_category_types.length == 0 %>
        <tr>
          <td colspan="3" style="color:#990000;text-align:center;">No sizing critera categories types found.</td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

<script type="text/javascript">
  $('#new_admin_sizing_criteria_category').colorbox();
  $('.edit_admin_sizing_criteria_category').colorbox();
  $('.new_admin_sizing_criteria_category_type').colorbox();
  $('.edit_admin_sizing_criteria_category_type').colorbox();
</script>

app/views/admin/sizing_criteria_categories/create.js.erb
<% if @sizing_criteria_category.errors.any?%>
	$(".error_messages").remove();	
	$("#new_sizing_criteria_category").prepend("<%= escape_javascript(error_messages_for(@sizing_criteria_category))%>");
	$.colorbox.resize();
<% else%>	
	$.colorbox.close();
	alert("New Sizing criteria category Created Successfully.");
	window.location.reload();
<% end%>

app/views/admin/sizing_criteria_categories/edit.html.erb
<div>
	<h4>Edit Sizing Criteria Category</h4>
	<%= render :partial => 'form', :locals => {:sizing_criteria_category => @sizing_criteria_category}%>
</div>

app/views/admin/sizing_criteria_categories/new.html.erb
<div>
	<h4>New Sizing Criteria Category</h4>
	<%= render :partial => 'form', :locals => {:sizing_criteria_category => @sizing_criteria_category}%>
</div>

app/views/admin/sizing_criteria_categories/update.js.erb
<% if @sizing_criteria_category.errors.any?%>
	$(".error_messages").remove();	
	$(".edit_sizing_criteria_category").prepend("<%= escape_javascript(error_messages_for(@sizing_criteria_category))%>");
	$.colorbox.resize();
<% else%>    
	alert("Sizing criteria category Updated Successfully.");
	window.location.reload();
<% end%>