config/routes.rb
App::Application.routes.draw do

  match "attachments/:attachment_type/:id", :to => 'attachments#get_attachment', :as => 'get_attachment'
  resources :attachments
  resources :comments

  devise_for :users

  match "home", :to => 'home#index', :as => :user_home

  match 'admin/project_process_units', :to => 'admin#project_process_units'
  match 'admin/client_projects', :to => 'admin#client_projects'
  match "admin", :to => 'admin#index', :as => :admin_home
  match "admin/sizing_data", :to => 'admin#sizing_data', :as => :default_data

  namespace :admin do

    resources :procures do
      collection do
        post "procure_rfq_sections"
        get "procure_rfq_sections_destroy"
        post "procure_additional_po_costs"
        get "procure_additional_po_costs_destroy"
      end
    end

    resources :pipings do

    end

    resources :mechanical_specifications do
      collection do
        post "itemtypes"
        get "itemtypes_destroy"
        post "vendor_requirement"
        get "vendor_requirement_destroy"
        post "datasheet"
        get "datasheet_destroy"
        get "datasheet_item_type"
      end
    end

    resources :relief_rate_calculation_views do
      collection do
        get 'view_generic'
        post 'save_generic'
      end
    end

    resources :scenario_summary_view_details do
      collection do
        get  'view_hydraulic_expansions'
        post 'save_hydraulic_expansions'
      end
    end

    resources :sizing_status_activities do
      collection do
        post 'change_status'
      end
    end

    match "summary_reports/:sizing", :to => 'summary_reports#sizing_summary_pdf', :as => :sizing_summary_pdf

    resources :company_users
    resources :groups
    resources :titles
    resources :units
    resources :roles

    resources :clients do
      member do
        get 'projects'
      end
    end

    resource :dashboard do
      collection do
        get "clients"
        get "projects"
        get "process_units"
        get "setdefault"
      end
    end

    resources :projects do
      member do
        get "edit/:step", :to => "projects#edit", :as => :edit_steps
        post "team_assignment"
        post "vendor_assignment"
        get "assign"
        get "assign_vendors"
        get "process_units"
        get "convert_and_round"
      end
      collection do
        get "project_case_details"
        get "project_details"
        post "update_case_details"
        get "vendor_setups"
        get "quotation"
        get "edit_vendor_schedule_setup"
        get "edit_purchase_vendor_schedule_setup"
        get "edit_as_built_vendor_schedule_setup"
        get "edit_with_shipment_vendor_schedule_setup"
        post "update_vendor_schedule_setup"
        post "update_purchase_vendor_schedule_setup"
        post "update_as_built_vendor_schedule_setup"
        post "update_with_shipment_vendor_schedule_setup"
        get "edit_request_for_quotation_setup"
        post "update_request_for_quotation_setup"
      end
    end

    resources :measure_units

    resources :measurements do
      collection do
        get 'get_measurement_sub_types'
      end
    end

    resources :measurement_sub_types
    resources :unit_of_measurements
    match '/heat_and_material_balances/get_sheet/:id/:name' => 'heat_and_material_balances#get_sheet', :as => 'get_hnm_balance_sheet'
    resources :heat_and_material_balances do
      member do
        post "delete_case"
      end
      collection do
        get "get_stream_nos"
      end
    end

    resources :pipe_roughness

    resources :sizing_criteria_categories
    resources :sizing_criteria_category_types
    resources :sizing_criterias do
      collection do
        get 'show_sizing_criterias'
        post 'add_sizing_criterias_to_project'
      end
    end

    resources :line_sizings do
      collection do
        get 'get_stream_values'
        get 'get_sizing_criteria_types'
        get 'get_sizing_criterias'
        get 'get_sizing_criteria_values'
        get 'line_sizing_summary'
        get 'sizing_criteria_calculation'
        get 'get_flow_regime'
        get 'design_condition_design'
        get 'straight_pipe_thickness_design'
        get 'target_two_phase_regime_estimate'
        get 'calculate_outer_diameter'
        post 'segment_sizing_criteria_calculation'
      end
      member do
        get 'clone'
      end
    end

    resources :vessel_sizings do
      collection do
        get 'get_feed_stream_nos'
        get 'get_top_outlet_stream_nos'
        get 'get_bottom_outlet_stream_nos'
        get 'get_vessel_sizing_hs_water_stream_nos'
        get 'vessel_sizing_summary'
        get 'filter_transfer_data'
        get 'reactor_transfer_data'
        get 'design_conditions_calculate'
        get 'mechanical_design_calculate'
        get 'get_nozzle_od'
        get 'feed_nozzle_calculation'
        get 'top_outlet_nozzle_calculation'
        get 'bottom_outlet_nozzle_calculation'
        get 'decanter_calculation'
        get 'horizontal_separator_calculation'
        get 'settler_calculation'
        get 'vertical_separator_calculation'
      end
      member do
        get 'clone'
      end

    end

    resources :pump_sizings do
      collection do
        get 'get_stream_values'
        get 'get_discharge_stream_nos'
        get 'clone_circuit_piping'
        get 'pump_sizing_summary'
        get 'suction_side_hydraulics'
        get 'discharge_side_hydraulics'
        get 'design_pump_centrifugal'
        get 'design_pump_reciprocation'
        get 'pump_suction_design'
        get 'equalize'
        get 'new_stream_property_changer'
        get 'get_change_properties_stream_values'
        get 'system_loss_calculate'
      end
      member do
        get 'clone'
      end
    end

    resources :compressor_sizings do
      collection do
        get 'get_stream_values'
        get 'get_discharge_stream_nos'
        get 'clone_circuit_piping'
        get 'compressor_sizing_summary'
        post 'add_compressor_sizing_mode'
        post 'edit_compressor_sizing_mode'
        post 'delete_compressor_sizing_mode'
        get 'suction_pipings'
        get 'discharges'
        get 'discharge_circuit_pipings'
        get 'discharge_circuit_piping_div'
        get 'suction_calculate'
        get 'discharge_calculate'
        get "centrifugal_design_calculate"
        get "reciprocation_design_calculate"
        get "rd_interstage_piping_calculate"
        get "cd_interstage_piping_calculate"
      end
      member do
        get 'clone'
      end
    end

    resources :driver_sizings do

    end

    resources :electric_motors do
      collection do
        get 'electric_motor_summary'
        get 'get_equiment_tag_by_equiment_type'
        get 'get_rotating_equipment_details'
      end
      member do
        get 'clone'
      end
    end

    resources :steam_turbines do
      collection do
        get 'get_stream_values'
        get 'steam_turbine_summary'
        get 'get_equiment_tag_by_equiment_type'
        get 'get_rotating_equipment_details'
        get 'steam_turbine_design_calculate'
        get 'estimate_efficiency_calculation'
      end
      member do
        get 'clone'
      end
    end

    resources :hydraulic_turbines do
      collection do
        get 'get_stream_values'
        get 'get_discharge_stream_nos'
        get 'hydraulic_turbine_summary'
        get 'suction_calculation'
        get 'get_equiment_tag_by_equiment_type'
        get 'get_rotating_equipment_details'
        get 'hprt_suctionside_hydraulics'
        get 'hprt_dischargeside_hydraulics'
        get 'hydraulic_turbine_design'
      end
      member do
        get 'clone'
      end
    end

    resources :turbo_expanders do
      collection do
        get 'get_stream_values'
        get 'get_expander_design_stream_values'
        get 'turbo_expanders_summary'
        get 'expander_design_calculation'
        get 'get_equiment_tag_by_equiment_type'
        get 'get_rotating_equipment_details'
      end
      member do
        get 'clone'
      end
    end

    resources :control_valve_sizings do
      collection do
        get 'get_stream_values'
        get 'get_discharge_stream_nos'
        get 'control_valve_sizing_summary'
        get 'bypass_design_calculation'
        get 'control_valve_design_calculation'
        get 'upstream_calculate'
        get 'downstream_calculate'
      end
      member do
        get 'clone'
      end
    end

    resources :flow_element_sizings do
      collection do
        get 'get_stream_values'
        get 'get_discharge_stream_nos'
        get 'flow_element_sizing_summary'
        get 'upstream_calculate'
        get 'downstream_calculate'
        get 'get_pipe_diameter'
        get 'get_orifice_types'
        get 'orifice_design'
      end
      member do
        get 'clone'
      end
    end

    resources :storage_tank_sizings do
      collection do
        get 'get_stream_values'
        get 'store_tank_sizing_summary'
        get 'design_conditions_calculate'
        get 'atm_low_pressure_storage_calculate'
        get 'pvapor_calculate'
        get 'pressure_storage_calculate'
        get 'mechanical_design_calculate'
        get 'atm_standardize_calculate'
        get 'ps_standardize_calculate'
      end
      member do
        get 'clone'
      end
    end

    resources :column_sizings do
      collection do
        get 'get_stream_values'
        get 'column_sizing_summary'
        get 'system_definition_calculation'
        get 'minimum_column_stages_calculation'
        get 'minimum_column_stages_winn_modified_calculation'
        post 'minimum_reflux_ratio_calculation'
      end
      member do
        get 'clone'
      end
    end

    resources :heat_exchanger_sizings do
      collection do
        get 'get_stream_values'
        get 'heat_exchanger_sizing_summary'
        get 'change_tube_od'
      end
      member do
        get 'clone'
      end
    end

app/views/admin/projects/destroy.js.erb
$('#project_<%= @project.id%>').fadeOut().remove();

app/views/admin/projects/edit_as_built_vendor_schedule_setup.html.erb
<link rel="stylesheet" href="http://jqueryui.com/web-base-template/themes/jqueryui.com/style.css">
<div style="min-width: 700px; min-height: 300px;">
  <h2><%= params[:item_type] %> </h2>

  <h3><%= @vendor_required_data.vendor_data_requirement %> for As Built</h3>

  <%= form_for @vendor_schedule_setup, :url => update_as_built_vendor_schedule_setup_admin_projects_path(:page => params[:page]), :html => {:method => :post, :remote => true} do |f| %>
    <%= f.hidden_field :id %>
    Notes
    <div class="form-element">
      <table>
        <td><%= f.text_area :as_built, :class => "text_area" %></td>
        <% if params[:page] == "item_tag" %>
          <td><p>Date: <%= f.text_field :date, :id => "datepicker" %></p></td>
        <% end %>
      </table>


      <br/>
      <%= f.submit "Update" %>
    </div>

  <% end %>
  <% if params[:page] == "item_tag" %>
    <fieldset class="project" style="margin-top:15px;">
      <legend>Attachments</legend>

      <input id="attachment_tab3" type="button" value="[+] Expand" onclick="toggle_visibility('div_attachment_tab3','attachment_tab3');">

      <div style="width:auto;" id="div_attachment_tab3">
        <%#= render :partial => "attachments/attachments", :locals => {:attachments => @attachments_tab1} %>
        <% @attachments_tab3.each do |attachment| %>
          <div class="attachment">
            <p class="name">
              <span class="applicable_span1">proposal</span>&nbsp; for&nbsp; <%= attachment.name %>
              <%= link_to attachment.attachment_file_name, get_attachment_path(attachment.attachable_type.downcase, attachment.id), :target => '_blank' %>
            </p>
            <blockquote>
              <p><%= attachment.description %></p>

            </blockquote>
            <div class="attachment_div">
              <small><%= attachment.user.name %></small>
              <span class="help-inline created_at">Created at <%= attachment.created_at.strftime('%d-%b-%Y %I:%M:%S %p') %></span>
            </div>
          </div>
        <% end %>
      </div>
      <br>

      <div class="new_attachment">
        <%= form_for @attachment, :url => url_for(:controller => '/attachments', :action => 'create'), :html => {:multipart => true, :style => "width:96.5%;", :class => "well form-inline"} do |f| %>
          <%= f.hidden_field :attachable_id %>
          <%= f.hidden_field :attachable_type %>
          <span class="file-wrapper">
      <%= f.file_field :attachment %>
            <span class="button">Select File</span>
    </span>
          <%= f.text_field :name, :placeholder => "Attachment Name" %>
          <%= f.text_field :description, :placeholder => "Attachment Description" %>
          <%= hidden_field_tag "attachment_vendor", "#{params[:item_proposal_id]}_#{params[:item_tag_id]}_as_built" %>
          <%= f.submit "Submit Attachment" %>
        <% end %>
      </div>


    </fieldset>
    <fieldset class="project" style="margin-top:15px;">
      <legend>Comments</legend>
      <%#= render :partial => "comments/comments", :locals => {:comments => @comments_tab4} %>
      <%#= render :partial => "comments/form", :locals => {:comment => @comment} %>
      <input id="comments_tab3" type="button" value="[+] Expand" onclick="toggle_visibility('div_comment_tab3','comments_tab3');">

      <div style="width:auto;" id="div_comment_tab3">
        <%#= render :partial => "comments/comments", :locals => {:comments => @comments_tab4} %>
        <% @comments_tab4.each do |comment| %>
          <div class="comment">
            <p class="title"><span class="applicable_span1">proposal</span>&nbsp; for <%= comment.title %></p>

            <p class="comment_content"><%= comment.comment %></p>

            <div class="comment_div">
              <small><%= comment.user.name %> -</small>
              <span class="created"> <small>Created
                at <%= comment.created_at.strftime('%d-%b-%Y %I:%M:%S %p') %></small></span>
            </div>
          </div>

        <% end %>
      </div>

      <div class="new_comment">
        <%= form_for @comment,:url => url_for(:controller => '/comments', :action => 'create'), :html => {:style => "width:100%;"} do |f| %>
          <%= f.hidden_field :commentable_id %>
          <%= f.hidden_field :commentable_type %>
          <div class="control-group">
            <%= f.label :title, :class => "control-label" %>
            <div class="controls">
              <%= f.text_field :title, :style => "width:99%;" %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :comment, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :comment, :style => "width:99%;", :rows => 4 %>
              <%= hidden_field_tag "attachment_vendor", "#{params[:item_proposal_id]}_#{params[:item_tag_id]}_as_built" %>
            </div>
          </div>
          <div class="control-group">
            <%= f.submit "Create" %>
          </div>
        <% end %>

      </div>
    </fieldset>
    <style>

      .form-element {
        min-width: 960px !important;
      }

    </style>
  <% end %>
  <style>
    .text_area {
      width: 640px;

      height: 100px;
      position: relative;
    }

    .form-element {
      min-width: 660px;
    }

    .attachment_div {
      bottom: 65px;
      float: right;
      padding-right: 10px;
      position: relative;
    }

    #div_attachment_tab3,#div_comment_tab3{
      display: none;
      width: 100% !important;
    }

    #attachment_tab3, #comments_tab3 {
      border: none;
      background: none;
    }

  </style>
  <script>
    function toggle_visibility(tbid, lnkid) {
      if (document.all) {
        document.getElementById(tbid).style.display = document.getElementById(tbid).style.display == "block" ? "none" : "block";
      }
      else {
        document.getElementById(tbid).style.display = document.getElementById(tbid).style.display == "table" ? "none" : "table";
      }
      document.getElementById(lnkid).value = document.getElementById(lnkid).value == "[-] Collapse" ? "[+] Expand" : "[-] Collapse";
    }
    $(function () {
      $("#datepicker").datepicker();
    });
  </script>
</div>

app/views/admin/projects/edit_purchase_vendor_schedule_setup.html.erb
<link rel="stylesheet" href="http://jqueryui.com/web-base-template/themes/jqueryui.com/style.css">
<div style="min-width: 700px; min-height: 300px;">
  <h2><%= params[:item_type] %> </h2>

  <h3><%= @vendor_required_data.vendor_data_requirement %> for Purchase</h3>


  <%= form_for @vendor_schedule_setup, :url => update_purchase_vendor_schedule_setup_admin_projects_path(:page => params[:page]), :html => {:method => :post, :remote => true} do |f| %>
    <%= f.hidden_field :id %>
    Notes
    <div class="form-element">
      <table>
        <td><%= f.text_area :purchase, :class => "text_area" %></td>
        <% if params[:page] == "item_tag" %>
          <td><p>Date: <%= f.text_field :date, :id => "datepicker" %></p></td>
        <% end %>
      </table>
      <br/>
      <%= f.submit "Update" %>
    </div>

  <% end %>
  <% if params[:page] == "item_tag" %>
    <fieldset class="project" style="margin-top:15px;">
      <legend>Attachments</legend>

      <input id="attachment_tab3" type="button" value="[+] Expand" onclick="toggle_visibility('div_attachment_tab3','attachment_tab3');">

      <div style="width:auto;" id="div_attachment_tab3">
        <%#= render :partial => "attachments/attachments", :locals => {:attachments => @attachments_tab1} %>
        <% @attachments_tab3.each do |attachment| %>
          <div class="attachment">
            <p class="name">
              <span class="applicable_span1">proposal</span>&nbsp; for&nbsp; <%= attachment.name %>
              <%= link_to attachment.attachment_file_name, get_attachment_path(attachment.attachable_type.downcase, attachment.id), :target => '_blank' %>
            </p>
            <blockquote>
              <p><%= attachment.description %></p>

            </blockquote>
            <div class="attachment_div">
              <small><%= attachment.user.name %></small>
              <span class="help-inline created_at">Created at <%= attachment.created_at.strftime('%d-%b-%Y %I:%M:%S %p') %></span>
            </div>
          </div>
        <% end %>
      </div>
      <br>

      <div class="new_attachment">
        <%= form_for @attachment, :url => url_for(:controller => '/attachments', :action => 'create'), :html => {:multipart => true, :style => "width:96.5%;", :class => "well form-inline"} do |f| %>
          <%= f.hidden_field :attachable_id %>
          <%= f.hidden_field :attachable_type %>
          <span class="file-wrapper">
      <%= f.file_field :attachment %>
            <span class="button">Select File</span>
    </span>
          <%= f.text_field :name, :placeholder => "Attachment Name" %>
          <%= f.text_field :description, :placeholder => "Attachment Description" %>
          <%= hidden_field_tag "attachment_vendor", "#{params[:item_proposal_id]}_#{params[:item_tag_id]}_purchase" %>
          <%= f.submit "Submit Attachment" %>
        <% end %>
      </div>


    </fieldset>
    <fieldset class="project" style="margin-top:15px;">
      <legend>Comments</legend>
      <%#= render :partial => "comments/comments", :locals => {:comments => @comments_tab4} %>
      <%#= render :partial => "comments/form", :locals => {:comment => @comment} %>
      <input id="comments_tab3" type="button" value="[+] Expand" onclick="toggle_visibility('div_comment_tab3','comments_tab3');">

      <div style="width:auto;" id="div_comment_tab3">
        <%#= render :partial => "comments/comments", :locals => {:comments => @comments_tab4} %>
        <% @comments_tab4.each do |comment| %>
          <div class="comment">
            <p class="title"><span class="applicable_span1">proposal</span>&nbsp; for <%= comment.title %></p>

            <p class="comment_content"><%= comment.comment %></p>

            <div class="comment_div">
              <small><%= comment.user.name %> -</small>
              <span class="created"> <small>Created
                at <%= comment.created_at.strftime('%d-%b-%Y %I:%M:%S %p') %></small></span>
            </div>
          </div>

        <% end %>
      </div>

      <div class="new_comment">
        <%= form_for @comment,:url => url_for(:controller => '/comments', :action => 'create'), :html => {:style => "width:100%;"} do |f| %>
          <%= f.hidden_field :commentable_id %>
          <%= f.hidden_field :commentable_type %>
          <div class="control-group">
            <%= f.label :title, :class => "control-label" %>
            <div class="controls">
              <%= f.text_field :title, :style => "width:99%;" %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :comment, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :comment, :style => "width:99%;", :rows => 4 %>
              <%= hidden_field_tag "attachment_vendor", "#{params[:item_proposal_id]}_#{params[:item_tag_id]}_purchase" %>
            </div>
          </div>
          <div class="control-group">
            <%= f.submit "Create" %>
          </div>
        <% end %>

      </div>
    </fieldset>
    <style>

      .form-element {
        min-width: 960px !important;
      }

    </style>
  <% end %>
  <style>
    .text_area {
      width: 650px;
      height: 100px;
      position: relative;
    }

    .form-element {
      min-width: 660px;
    }
    .attachment_div {
      bottom: 65px;
      float: right;
      padding-right: 10px;
      position: relative;
    }

    #div_attachment_tab3,#div_comment_tab3{
      display: none;
      width: 100% !important;
    }

    #attachment_tab3, #comments_tab3 {
      border: none;
      background: none;
    }

  </style>
  <script>
    function toggle_visibility(tbid, lnkid) {
      if (document.all) {
        document.getElementById(tbid).style.display = document.getElementById(tbid).style.display == "block" ? "none" : "block";
      }
      else {
        document.getElementById(tbid).style.display = document.getElementById(tbid).style.display == "table" ? "none" : "table";
      }
      document.getElementById(lnkid).value = document.getElementById(lnkid).value == "[-] Collapse" ? "[+] Expand" : "[-] Collapse";
    }
    $(function() {
      $( "#datepicker" ).datepicker();
    });
  </script>
</div>

app/views/admin/projects/edit_with_shipment_vendor_schedule_setup.html.erb
<link rel="stylesheet" href="http://jqueryui.com/web-base-template/themes/jqueryui.com/style.css">
<div style="min-width: 700px; min-height: 300px;">
  <h2><%= params[:item_type] %> </h2>
<h3><%=@vendor_required_data.vendor_data_requirement %> with Shipment</h3>


<%= form_for @vendor_schedule_setup, :url => update_with_shipment_vendor_schedule_setup_admin_projects_path(:page => params[:page]), :html => {:method => :post, :remote => true} do |f| %>
  <%= f.hidden_field :id %>
  Notes
  <div class="form-element">
    <table>
      <td><%= f.text_area :with_shipment, :class => "text_area" %></td>
      <% if params[:page] == "item_tag" %>
        <td><p>Date: <%= f.text_field :date, :id => "datepicker" %></p></td>
      <% end %>
    </table>
    <br/>
    <%= f.submit "Update" %>
  </div>

<% end %>
  <% if params[:page] == "item_tag" %>
    <fieldset class="project" style="margin-top:15px;">
      <legend>Attachments</legend>

      <input id="attachment_tab3" type="button" value="[+] Expand" onclick="toggle_visibility('div_attachment_tab3','attachment_tab3');">

      <div style="width:auto;" id="div_attachment_tab3">
        <%#= render :partial => "attachments/attachments", :locals => {:attachments => @attachments_tab1} %>
        <% @attachments_tab3.each do |attachment| %>
          <div class="attachment">
            <p class="name">
              <span class="applicable_span1">proposal</span>&nbsp; for&nbsp; <%= attachment.name %>
              <%= link_to attachment.attachment_file_name, get_attachment_path(attachment.attachable_type.downcase, attachment.id), :target => '_blank' %>
            </p>
            <blockquote>
              <p><%= attachment.description %></p>

            </blockquote>
            <div class="attachment_div">
              <small><%= attachment.user.name %></small>
              <span class="help-inline created_at">Created at <%= attachment.created_at.strftime('%d-%b-%Y %I:%M:%S %p') %></span>
            </div>
          </div>
        <% end %>
      </div>
      <br>

      <div class="new_attachment">
        <%= form_for @attachment, :url => url_for(:controller => '/attachments', :action => 'create'), :html => {:multipart => true, :style => "width:96.5%;", :class => "well form-inline"} do |f| %>
          <%= f.hidden_field :attachable_id %>
          <%= f.hidden_field :attachable_type %>
          <span class="file-wrapper">
      <%= f.file_field :attachment %>
            <span class="button">Select File</span>
    </span>
          <%= f.text_field :name, :placeholder => "Attachment Name" %>
          <%= f.text_field :description, :placeholder => "Attachment Description" %>
          <%= hidden_field_tag "attachment_vendor", "#{params[:item_proposal_id]}_#{params[:item_tag_id]}_with_shipment" %>
          <%= f.submit "Submit Attachment" %>
        <% end %>
      </div>


    </fieldset>
    <fieldset class="project" style="margin-top:15px;">
      <legend>Comments</legend>
      <%#= render :partial => "comments/comments", :locals => {:comments => @comments_tab4} %>
      <%#= render :partial => "comments/form", :locals => {:comment => @comment} %>
      <input id="comments_tab3" type="button" value="[+] Expand" onclick="toggle_visibility('div_comment_tab3','comments_tab3');">

      <div style="width:auto;" id="div_comment_tab3">
        <%#= render :partial => "comments/comments", :locals => {:comments => @comments_tab4} %>
        <% @comments_tab4.each do |comment| %>
          <div class="comment">
            <p class="title"><span class="applicable_span1">proposal</span>&nbsp; for <%= comment.title %></p>

            <p class="comment_content"><%= comment.comment %></p>

            <div class="comment_div">
              <small><%= comment.user.name %> -</small>
              <span class="created"> <small>Created
                at <%= comment.created_at.strftime('%d-%b-%Y %I:%M:%S %p') %></small></span>
            </div>
          </div>

        <% end %>
      </div>

      <div class="new_comment">
        <%= form_for @comment,:url => url_for(:controller => '/comments', :action => 'create'), :html => {:style => "width:100%;"} do |f| %>
          <%= f.hidden_field :commentable_id %>
          <%= f.hidden_field :commentable_type %>
          <div class="control-group">
            <%= f.label :title, :class => "control-label" %>
            <div class="controls">
              <%= f.text_field :title, :style => "width:99%;" %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :comment, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :comment, :style => "width:99%;", :rows => 4 %>
              <%= hidden_field_tag "attachment_vendor", "#{params[:item_proposal_id]}_#{params[:item_tag_id]}_with_shipment" %>
            </div>
          </div>
          <div class="control-group">
            <%= f.submit "Create" %>
          </div>
        <% end %>

      </div>
    </fieldset>
    <style>

      .form-element {
        min-width: 960px !important;
      }

    </style>
  <% end %>
  <style>
    .text_area {
      width: 650px;
      height: 100px;
      position: relative;
    }

    .form-element {
      min-width: 660px;
    }
    .attachment_div {
      bottom: 65px;
      float: right;
      padding-right: 10px;
      position: relative;
    }

    #div_attachment_tab3,#div_comment_tab3{
      display: none;
      width: 100% !important;
    }

    #attachment_tab3, #comments_tab3 {
      border: none;
      background: none;
    }
  </style>
  <script>
    function toggle_visibility(tbid, lnkid) {
      if (document.all) {
        document.getElementById(tbid).style.display = document.getElementById(tbid).style.display == "block" ? "none" : "block";
      }
      else {
        document.getElementById(tbid).style.display = document.getElementById(tbid).style.display == "table" ? "none" : "table";
      }
      document.getElementById(lnkid).value = document.getElementById(lnkid).value == "[-] Collapse" ? "[+] Expand" : "[-] Collapse";
    }
    $(function() {
      $( "#datepicker" ).datepicker();
    });
  </script>
</div>

app/views/admin/projects/update_case_details.js.erb
alert('hello world');

app/views/admin/projects/update_vendor_schedule_setup.js.erb
$.colorbox.close();